@api_HostAddress = http://localhost:5246


###
GET {{api_HostAddress}}/api/stock
Accept: application/json

###
GET {{api_HostAddress}}/api/stock/3
Accept: application/json


###
POST {{api_HostAddress}}/api/stock/
Accept: application/json
Content-Type: application/json

{
  "symbol": "DFDFDF",
  "company": "MWM Corp",
  "purchase": 90.50,
  "lastDiv": 2.75,
  "industry": "Technology",
  "marketCap": 4934893
}

###
PUT {{api_HostAddress}}/api/stock/12
Accept: application/json
Content-Type: application/json

{
  "symbol": "__MWM__",
  "company": "MMMMM",
  "purchase": 205.50,
  "lastDiv": 2,
  "industry": "Technology",
  "marketCap": 75934893
}

###
DELETE {{api_HostAddress}}/api/stock/12
